version: '3.0'
services:
  crawler_vtsc:
    image: username992/crawler:8.1
    hostname: "vtsc"
    command: poetry run celery -A vtuberdata.tasks.worker worker --loglevel=info --concurrency=1  --hostname=%h -Q vtsc
    restart: always
    # swarm 設定
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.crawler_vtsc == true]
    environment:
      - TZ=Asia/Taipei
    networks:
        - my_network

networks:
  my_network:
    # 加入已經存在的網路
    external: true